#include "board_resources.h"

#include <xparameters.h>

#define FC_NO_INTERRUPT (-1)

static const fc_board_resource_t g_board_resources[] = {
    {"ps_gpio", XPAR_PS7_GPIO_0_DEVICE_ID, XPAR_PS7_GPIO_0_BASEADDR,
     XPAR_PS7_GPIO_0_HIGHADDR, FC_NO_INTERRUPT, FC_RESOURCE_READ_ONLY, false},
    {"ps_uart0", XPAR_PS7_UART_0_DEVICE_ID, XPAR_PS7_UART_0_BASEADDR,
     XPAR_PS7_UART_0_HIGHADDR, XPAR_PS7_UART_0_INT_SOURCE,
     FC_RESOURCE_COMMUNICATION, true},
    {"ps_can0", XPAR_PS7_CAN_0_DEVICE_ID, XPAR_PS7_CAN_0_BASEADDR,
     XPAR_PS7_CAN_0_HIGHADDR, FC_NO_INTERRUPT, FC_RESOURCE_COMMUNICATION, false},
    {"ps_can1", XPAR_PS7_CAN_1_DEVICE_ID, XPAR_PS7_CAN_1_BASEADDR,
     XPAR_PS7_CAN_1_HIGHADDR, FC_NO_INTERRUPT, FC_RESOURCE_COMMUNICATION, false},
    {"pl_uart0", XPAR_AXI_4CH_UART_PL_0_DEVICE_ID,
     XPAR_AXI_4CH_UART_PL_0_S00_AXI_BASEADDR,
     XPAR_AXI_4CH_UART_PL_0_S00_AXI_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_COMMUNICATION, false},
    {"pl_uart1", XPAR_AXI_4CH_UART_PL_1_DEVICE_ID,
     XPAR_AXI_4CH_UART_PL_1_S00_AXI_BASEADDR,
     XPAR_AXI_4CH_UART_PL_1_S00_AXI_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_COMMUNICATION, false},
    {"ad7606_0", XPAR_AXI_AD7606_0_DEVICE_ID,
     XPAR_AXI_AD7606_0_S00_AXI_BASEADDR,
     XPAR_AXI_AD7606_0_S00_AXI_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"ad7606_1", XPAR_AXI_AD7606_1_DEVICE_ID,
     XPAR_AXI_AD7606_1_S00_AXI_BASEADDR,
     XPAR_AXI_AD7606_1_S00_AXI_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"iic_main_current", XPAR_AXI_IIC_AXI_IIC_MAIN_CURRENT_DEVICE_ID,
     XPAR_AXI_IIC_AXI_IIC_MAIN_CURRENT_BASEADDR,
     XPAR_AXI_IIC_AXI_IIC_MAIN_CURRENT_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"iic_pd_temp", XPAR_AXI_IIC_AXI_IIC_PD_TEMP_DEVICE_ID,
     XPAR_AXI_IIC_AXI_IIC_PD_TEMP_BASEADDR,
     XPAR_AXI_IIC_AXI_IIC_PD_TEMP_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"iic_temp", XPAR_AXI_IIC_AXI_IIC_TEMP_DEVICE_ID,
     XPAR_AXI_IIC_AXI_IIC_TEMP_BASEADDR,
     XPAR_AXI_IIC_AXI_IIC_TEMP_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"gpio_28v_input", XPAR_AXI_GPIO_CTRL_AXI_GPIO_28V_IN_DEVICE_ID,
     XPAR_AXI_GPIO_CTRL_AXI_GPIO_28V_IN_BASEADDR,
     XPAR_AXI_GPIO_CTRL_AXI_GPIO_28V_IN_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"gpio_no_source_28v", XPAR_AXI_GPIO_NOSOURCE_28VIN_DEVICE_ID,
     XPAR_AXI_GPIO_NOSOURCE_28VIN_BASEADDR,
     XPAR_AXI_GPIO_NOSOURCE_28VIN_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_READ_ONLY, false},
    {"gpio_led", XPAR_AXI_GPIO_LED_DEVICE_ID, XPAR_AXI_GPIO_LED_BASEADDR,
     XPAR_AXI_GPIO_LED_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_DANGEROUS_OUTPUT, false},
    {"gpio_sx_pmos", XPAR_AXI_GPIO_CTRL_AXI_GPIO_SX_PMOS_DEVICE_ID,
     XPAR_AXI_GPIO_CTRL_AXI_GPIO_SX_PMOS_BASEADDR,
     XPAR_AXI_GPIO_CTRL_AXI_GPIO_SX_PMOS_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_DANGEROUS_OUTPUT, false},
    {"gpio_sx_relay", XPAR_AXI_GPIO_CTRL_AXI_GPIO_SX_RELAY_DEVICE_ID,
     XPAR_AXI_GPIO_CTRL_AXI_GPIO_SX_RELAY_BASEADDR,
     XPAR_AXI_GPIO_CTRL_AXI_GPIO_SX_RELAY_HIGHADDR, FC_NO_INTERRUPT,
     FC_RESOURCE_DANGEROUS_OUTPUT, false},
    {"pwm", 0u, XPAR_PWM_PWM_TOP_0_BASEADDR, XPAR_PWM_PWM_TOP_0_HIGHADDR,
     FC_NO_INTERRUPT, FC_RESOURCE_DANGEROUS_OUTPUT, false}
};

size_t fc_board_resource_count(void)
{
    return sizeof(g_board_resources) / sizeof(g_board_resources[0]);
}

fc_status_t fc_board_resource_get(size_t index,
                                  const fc_board_resource_t **resource)
{
    if (resource == NULL) {
        return FC_STATUS_INVALID_ARGUMENT;
    }

    if (index >= fc_board_resource_count()) {
        *resource = NULL;
        return FC_STATUS_INVALID_ARGUMENT;
    }

    *resource = &g_board_resources[index];
    return FC_STATUS_OK;
}
